source(misegundoscript)
variableUno<-funcionUno(1,2)
variableDos<-velocidad(10,2)
variableTres<-algebra(2,5,6)
variablecuatro<-area(pi,5)
variablecinco<-corona(pi,4,2)
variableseis<-casa(6000,5)
variablesiete<-home(6000,5)
