#rm(list= ls())
source(misegundoscript.R)
variableUno<-funcionUno(1,2)
variableDos<-velocidad(10,2)
variableTres<-algebra(2,5,6)
variablecuatro<-area(pi,5)
variablecinco<-corona(4,3)
variableseis<-casa(6000,5)
variablesiete<-home(6000,6)
variableocho<-areacirc(2)
